apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-service
spec:
  selector:
    app: todo-app-backend
  ports:
    - protocol: TCP
      port:  80
      targetPort:  5000
  type: NodePort
