apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-app-db-pv
spec:
  capacity:
    storage:  1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data"
