apiVersion: v1
kind: Service
metadata:
  name: todo-app-frontend-service
spec:
  selector:
    app: todo-app-frontend
  ports:
    - protocol: TCP
      port:  80
      targetPort:  3000
  type: NodePort